-- MySQL Script generated by MySQL Workbench
-- 09/18/14 16:21:26
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema sgc
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sgc` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `sgc` ;

-- -----------------------------------------------------
-- Table `sgc`.`AREA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sgc`.`AREA` (
  `pk` BIGINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NULL,
  PRIMARY KEY (`pk`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sgc`.`TYPE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sgc`.`TYPE` (
  `pk` BIGINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NULL,
  `guest_access` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`pk`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sgc`.`PLACE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sgc`.`PLACE` (
  `pk` BIGINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NULL,
  PRIMARY KEY (`pk`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sgc`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sgc`.`user` (
  `pk` BIGINT NOT NULL AUTO_INCREMENT,
  `user_name` VARCHAR(50) NULL,
  `user_surname` VARCHAR(50) NULL,
  `user_password` VARCHAR(50) NULL,
  `user_email` VARCHAR(100) NULL,
  `user_lavel` TINYINT NULL DEFAULT 1 COMMENT '0 = admin, 1 = user',
  `user_status` TINYINT(1) NULL DEFAULT 1,
  PRIMARY KEY (`pk`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sgc`.`time`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sgc`.`time` (
  `pk` INT NOT NULL AUTO_INCREMENT,
  `time_lange` VARCHAR(45) NULL,
  PRIMARY KEY (`pk`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sgc`.`CRIME`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sgc`.`CRIME` (
  `pk` BIGINT NOT NULL AUTO_INCREMENT,
  `crime_id` VARCHAR(15) NULL,
  `crime_date` DATE NULL,
  `crime_lat` DOUBLE NULL,
  `crime_lng` DOUBLE NULL,
  `crime_detail` VARCHAR(1023) NULL,
  `crime_level` INT NULL,
  `area_pk` BIGINT NULL,
  `type_pk` BIGINT NULL,
  `place_pk` BIGINT NULL,
  `user_pk` BIGINT NULL,
  `time_pk` INT NULL,
  PRIMARY KEY (`pk`),
  INDEX `fk_CRIME_CRIME_AREA1_idx` (`area_pk` ASC),
  INDEX `fk_CRIME_CRIME_TYPE1_idx` (`type_pk` ASC),
  INDEX `fk_CRIME_CRIME_PLACE1_idx` (`place_pk` ASC),
  INDEX `fk_CRIME_user1_idx` (`user_pk` ASC),
  INDEX `fk_CRIME_TIME1_idx` (`time_pk` ASC),
  CONSTRAINT `fk_CRIME_CRIME_AREA1`
    FOREIGN KEY (`area_pk`)
    REFERENCES `sgc`.`AREA` (`pk`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CRIME_CRIME_TYPE1`
    FOREIGN KEY (`type_pk`)
    REFERENCES `sgc`.`TYPE` (`pk`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CRIME_CRIME_PLACE1`
    FOREIGN KEY (`place_pk`)
    REFERENCES `sgc`.`PLACE` (`pk`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CRIME_user1`
    FOREIGN KEY (`user_pk`)
    REFERENCES `sgc`.`user` (`pk`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CRIME_TIME1`
    FOREIGN KEY (`time_pk`)
    REFERENCES `sgc`.`time` (`pk`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sgc`.`IMAGE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sgc`.`IMAGE` (
  `pk` BIGINT NOT NULL AUTO_INCREMENT,
  `crime_pk` BIGINT NULL,
  PRIMARY KEY (`pk`),
  INDEX `fk_CRIME_IMAGE_CRIME1_idx` (`crime_pk` ASC),
  CONSTRAINT `fk_CRIME_IMAGE_CRIME1`
    FOREIGN KEY (`crime_pk`)
    REFERENCES `sgc`.`CRIME` (`pk`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `sgc` ;

-- -----------------------------------------------------
-- procedure find_all
-- -----------------------------------------------------

DELIMITER $$
USE `sgc`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `find_all`(item varchar(20), user_seq BIGINT(20), n INT)
BEGIN
	CASE item
		WHEN "crime" THEN SELECT * FROM `crime`;
		WHEN "area" THEN SELECT * FROM `crime_area`;
		WHEN "image" THEN SELECT * FROM `crime_image`;
		WHEN "place" THEN SELECT * FROM `crime_place`;
		WHEN "type" THEN SELECT * FROM `crime_type`;
		WHEN "type_group" THEN SELECT * FROM `type_group`;
		WHEN "user" THEN SELECT * FROM `user`;
		WHEN "log" THEN SELECT * FROM `log`;
	END CASE;
END$$

DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
