-- MySQL Script generated by MySQL Workbench
-- 11/03/14 01:25:13
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema sgc
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sgc` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `sgc` ;

-- -----------------------------------------------------
-- Table `sgc`.`CHECK_POINT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sgc`.`CHECK_POINT` (
  `pk` BIGINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NULL,
  PRIMARY KEY (`pk`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sgc`.`AREA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sgc`.`AREA` (
  `pk` BIGINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NULL,
  PRIMARY KEY (`pk`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sgc`.`PLACE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sgc`.`PLACE` (
  `pk` BIGINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NULL,
  PRIMARY KEY (`pk`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sgc`.`TYPE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sgc`.`TYPE` (
  `pk` BIGINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NULL,
  `level` TINYINT NOT NULL DEFAULT 1 COMMENT '0 = guest' /* comment truncated */ /*1 = user*/,
  PRIMARY KEY (`pk`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sgc`.`time`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sgc`.`time` (
  `pk` INT NOT NULL AUTO_INCREMENT,
  `time_lange` VARCHAR(45) NULL,
  PRIMARY KEY (`pk`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sgc`.`TITLE_NAME`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sgc`.`TITLE_NAME` (
  `pk` BIGINT NOT NULL AUTO_INCREMENT,
  `title_name` VARCHAR(45) NULL COMMENT 'คำนำหน้าชื่อ',
  PRIMARY KEY (`pk`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sgc`.`USER`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sgc`.`USER` (
  `pk` BIGINT NOT NULL AUTO_INCREMENT,
  `title_name_pk` BIGINT NULL,
  `name` VARCHAR(31) NULL,
  `last_name` VARCHAR(31) NULL,
  `e_mail` VARCHAR(63) NULL,
  `user_name` VARCHAR(31) NULL,
  `password` VARCHAR(31) NULL,
  `status` TINYINT(1) NULL DEFAULT 1,
  `level` TINYINT NOT NULL DEFAULT 1 COMMENT '1 = user' /* comment truncated */ /*2 = admin
3 = user and admin*/,
  PRIMARY KEY (`pk`),
  INDEX `fk_USER_TITLE1_idx` (`title_name_pk` ASC),
  UNIQUE INDEX `user_name_UNIQUE` (`user_name` ASC),
  UNIQUE INDEX `e_mail_UNIQUE` (`e_mail` ASC),
  CONSTRAINT `fk_USER_TITLE1`
    FOREIGN KEY (`title_name_pk`)
    REFERENCES `sgc`.`TITLE_NAME` (`pk`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sgc`.`CRIME`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sgc`.`CRIME` (
  `pk` BIGINT NOT NULL AUTO_INCREMENT,
  `crime_id` VARCHAR(15) NULL,
  `crime_date` DATE NULL,
  `crime_lat` DOUBLE NULL,
  `crime_lng` DOUBLE NULL,
  `crime_detail` VARCHAR(1023) NULL,
  `crime_level` TINYINT NULL,
  `area_pk` BIGINT NULL COMMENT ' ',
  `type_pk` BIGINT NULL,
  `place_pk` BIGINT NULL,
  `time_pk` INT NULL,
  `person` VARCHAR(125) NULL DEFAULT NULL,
  `create_date` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `update_date` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `create_by_user_pk` BIGINT NULL,
  `update_by_user_pk` BIGINT NULL,
  `check_point_pk` BIGINT NOT NULL,
  PRIMARY KEY (`pk`),
  INDEX `fk_CRIME_CRIME_AREA1_idx` (`area_pk` ASC),
  INDEX `fk_CRIME_CRIME_TYPE1_idx` (`type_pk` ASC),
  INDEX `fk_CRIME_CRIME_PLACE1_idx` (`place_pk` ASC),
  INDEX `fk_CRIME_TIME1_idx` (`time_pk` ASC),
  INDEX `fk_CRIME_PERSON1_idx` (`person` ASC),
  INDEX `fk_CRIME_USER1_idx` (`create_by_user_pk` ASC),
  INDEX `fk_CRIME_USER2_idx` (`update_by_user_pk` ASC),
  INDEX `fk_CRIME_CHECK_POINT1_idx` (`check_point_pk` ASC),
  CONSTRAINT `fk_CRIME_CHECK_POINT1`
    FOREIGN KEY (`check_point_pk`)
    REFERENCES `sgc`.`CHECK_POINT` (`pk`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CRIME_CRIME_AREA1`
    FOREIGN KEY (`area_pk`)
    REFERENCES `sgc`.`AREA` (`pk`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CRIME_CRIME_PLACE1`
    FOREIGN KEY (`place_pk`)
    REFERENCES `sgc`.`PLACE` (`pk`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CRIME_CRIME_TYPE1`
    FOREIGN KEY (`type_pk`)
    REFERENCES `sgc`.`TYPE` (`pk`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CRIME_TIME`
    FOREIGN KEY (`time_pk`)
    REFERENCES `sgc`.`time` (`pk`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CRIME_USER1`
    FOREIGN KEY (`create_by_user_pk`)
    REFERENCES `sgc`.`USER` (`pk`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CRIME_USER2`
    FOREIGN KEY (`update_by_user_pk`)
    REFERENCES `sgc`.`USER` (`pk`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sgc`.`IMAGE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sgc`.`IMAGE` (
  `pk` BIGINT NOT NULL AUTO_INCREMENT,
  `crime_pk` BIGINT NULL,
  PRIMARY KEY (`pk`),
  INDEX `fk_CRIME_IMAGE_CRIME1_idx` (`crime_pk` ASC),
  CONSTRAINT `fk_CRIME_IMAGE_CRIME1`
    FOREIGN KEY (`crime_pk`)
    REFERENCES `sgc`.`CRIME` (`pk`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sgc`.`PERSON`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sgc`.`PERSON` (
  `pk` BIGINT NOT NULL AUTO_INCREMENT,
  `TITLE_pk` BIGINT NULL,
  `person_name` VARCHAR(31) NULL,
  `person_lasname` VARCHAR(31) NULL,
  `person_phone` VARCHAR(15) NULL,
  PRIMARY KEY (`pk`),
  INDEX `fk_PERSON_TITLE1_idx` (`TITLE_pk` ASC),
  CONSTRAINT `fk_PERSON_TITLE1`
    FOREIGN KEY (`TITLE_pk`)
    REFERENCES `sgc`.`TITLE_NAME` (`pk`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `sgc` ;

-- -----------------------------------------------------
-- procedure find_all
-- -----------------------------------------------------

DELIMITER $$
USE `sgc`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `find_all`(item varchar(20), user_seq BIGINT(20), n INT)
BEGIN
	CASE item
		WHEN "crime" THEN SELECT * FROM `crime`;
		WHEN "area" THEN SELECT * FROM `crime_area`;
		WHEN "image" THEN SELECT * FROM `crime_image`;
		WHEN "place" THEN SELECT * FROM `crime_place`;
		WHEN "type" THEN SELECT * FROM `crime_type`;
		WHEN "type_group" THEN SELECT * FROM `type_group`;
		WHEN "user" THEN SELECT * FROM `user`;
		WHEN "log" THEN SELECT * FROM `log`;
	END CASE;
END$$

DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
